version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/site-index"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/site-index-cli"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/vite-plugin-site-index"
    schedule:
      interval: "weekly"
